### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by aayush-506**

### CODE REVIEW

**Comment by narasimha-1511** [comment]
Hey can you make the footer sticky at the bottom .. 
Current Behaviour is no good..

Even remove that my account and withlist at bottom right corner

**Comment by aayush-506** [comment]
okay I will update it

**Comment by aayush-506** [comment]
> Hey can you make the footer sticky at the bottom .. Current Behaviour is no good..
> 
> Even remove that my account and withlist at bottom right corner

**Comment by narasimha-1511** [comment]
hey @aayush-506 ,
I just Want You to remove the complete 'My Account,login ...' 
In the Third Row

**Pull request merged**
